//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elawyerWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceHeader()
        {
            this.InvoiceLine = new HashSet<InvoiceLine>();
        }
    
        public int No { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int NoUser { get; set; }
        public int NoIssue { get; set; }
        public int NoStatus { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLine { get; set; }
        public virtual Issue Issue { get; set; }
        public virtual InvoiceStatus InvoiceStatus { get; set; }
    }
}
